apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newnginx
  template:
    metadata:
      labels:
        app: newnginx
    spec:
      containers:
        - name: my-nginx
          image: anjucoursera1/nginxcourseraapp
          ports: 
            - containerPort: 80